### ISSUE TITLE
Run emulator and find many repeated cycles in the .out files.

### ISSUE THREAD

**Issue by sjtu-sp** [freechipsproject/rocket-chip#1542] opened 2018-07-18 04:39 UTC
I  run assembly tests like the README.

cd emulator
make output/rv64ui-p-add.out

and found there are many repeated cycles in the .out file, like this:

 20 [0] pc=[17244031d] W[r 0=0000000000000000][0] R[r21=121b3be56cb860ed] R[r23=e5ee274bf7bd0031] inst=[b57a5053] unknown
C0:         21 [1] pc=[000010040] W[r10=0000000000000000][1] R[r 0=0000000000000000] R[r20=e5ee274bf7bd0033] inst=[f1402573] csrr    a0, mhartid
C0:         22 [1] pc=[000010044] W[r11=0000000000010044][1] R[r 0=0000000000000000] R[r 0=0000000000000000] inst=[00000597] auipc   a1, 0x0
C0:         23 [1] pc=[000010048] W[r11=0000000000010080][1] R[r11=0000000000010044] R[r28=e5ee274bf7bd0033] inst=[03c58593] addi    a1, a1, 60
C0:         24 [1] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         25 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=a80b1b412d0d90d3] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         26 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         27 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         28 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         29 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         30 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         31 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         32 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         33 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         34 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         35 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         36 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         37 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         38 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         39 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         40 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         41 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         42 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         43 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         44 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         45 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         46 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         47 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         48 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         49 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         50 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         51 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         52 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         53 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         54 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         55 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         56 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         57 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         58 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         59 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         60 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         61 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         62 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         63 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         64 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         65 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         66 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         67 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         68 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         69 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         70 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         71 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         72 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         73 [0] pc=[00001004c] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 5=e5ee274bf7bd0033] inst=[10500073] wfi (args unknown)
C0:         74 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         75 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         76 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         77 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         78 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         79 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         80 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         81 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         82 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         83 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         84 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         85 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         86 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         87 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         88 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         89 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         90 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         91 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         92 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         93 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         94 [0] pc=[000010050] W[r 0=0000000000000000][0] R[r31=0000000000000000] R[r29=e5ee274bf7bd0033] inst=[0000bff5] j       pc - 4
C0:         95 [1] pc=[000000800] W[r 0=0000000000000804][1] R[r 0=0000000000000000] R[r12=e5ee274bf7bd0033] inst=[00c0006f] j       pc + 0xc
C0:         96 [0] pc=[000000800] W[r 0=0000000000000804][0] R[r 0=0000000000000000] R[r12=e5ee274bf7bd0033] inst=[00c0006f] j       pc + 0xc
C0:         97 [0] pc=[000000800] W[r 0=0000000000000804][0] R[r 0=0000000000000000] R[r12=e5ee274bf7bd0033] inst=[00c0006f] j       pc + 0xc
C0:         98 [0] pc=[000000800] W[r 0=0000000000000804][0] R[r 0=0000000000000000] R[r12=e5ee274bf7bd0033] inst=[00c0006f] j       pc + 0xc

I want to know if this is correct, and if it's incorrect, what should I do to fix it?

Thanks a lot!

**Comment by colinschmidt** [comment] 2018-07-18 14:29
The second column (either `[0]` or `[1]`) shows whether the instruction committed, i.e. finished executing. So if an instruction takes multiple cycles (due to stalls, cache misses, etc.) it can appear in the output file multiple times.
So this is expected behavior and your trace is probably correct.

**Closed by colinschmidt** 2018-07-18 14:29 UTC
