### ISSUE TITLE
scala to verilog

### ISSUE THREAD

**Issue by mayankagnisys** [freechipsproject/rocket-chip#1223] opened 2018-02-02 05:37 UTC
Hi everyone,
 I am unable to convert alu.scala to alu.v.
 mayank@mayank-Lenovo-B590:~/rocket-chip/riscv-tools/verilator/src/main/scala$ sbt compile
 
[info] Loading project definition from /home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/project
[info] Set current project to scala (in build file:/home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 1 Scala source to /home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/target/scala-2.12/classes ...
[error] /home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/ALU.scala:6:8: not found: object Chisel
[error] import Chisel._
[error]        ^
[error] /home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/ALU.scala:7:29: object config is not a member of package freechips.rocketchip
[error] import freechips.rocketchip.config.Parameters
[error]                             ^
[error] /home/mayank/rocket-chip/riscv-tools/verilator/src/main/scala/ALU.scala:8:29: object tile is not a member of package freechips.rocketchip
[error] import freechips.rocketchip.tile.CoreModule

Thanks & regards
Mayank

**Comment by jackkoenig** [comment] 2018-02-06 19:30
Duplicate of https://github.com/freechipsproject/rocket-chip/issues/1213

**Closed by jackkoenig** 2018-02-06 19:30 UTC
